Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/main.py", line 7, in <module>
    from plotter import (
  File "/mnt/aiongpfs/users/mnaseh/ensemble-forecasters-hpc/plotter.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[11260,1],6]
  Exit code:    1
--------------------------------------------------------------------------
